# Generated by Django 3.2.13 on 2024-08-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitedetail',
            name='linked_by',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
