# Generated by Django 3.2.13 on 2024-08-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_websitedetail_linked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitedetail',
            name='name',
        ),
        migrations.AddField(
            model_name='websitedetail',
            name='first_name',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitedetail',
            name='second_name',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
