# Generated by Django 3.2.13 on 2024-08-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20240817_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitedetail',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='pics/'),
            preserve_default=False,
        ),
    ]
