# Generated by Django 3.2.13 on 2024-08-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_websitedetail_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitedetail',
            name='about_me',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
