# Generated by Django 3.2.13 on 2024-08-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_websitedetail_about_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
    ]
