# Generated by Django 3.2.13 on 2024-08-23 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_academicsfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('sub_title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('filter_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academics', to='Main.academicsfilter')),
            ],
        ),
    ]
