# Generated by Django 3.2.13 on 2024-08-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_academic'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic',
            name='image',
            field=models.ImageField(default='', upload_to='pics/'),
            preserve_default=False,
        ),
    ]
