# Generated by Django 3.2.13 on 2024-08-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_academic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsfilter',
            name='slug',
            field=models.SlugField(blank=True, default='slug', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
