# Generated by Django 3.2.13 on 2024-08-27 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_auto_20240823_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=125)),
                ('slug', models.SlugField(blank=True, default='slug', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('sub_title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pics/')),
                ('filter_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Main.projectfilter')),
            ],
        ),
    ]
