# Generated by Django 3.2.13 on 2024-08-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20240828_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitedetail',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='websitedetail',
            name='second_name',
        ),
        migrations.AddField(
            model_name='academic',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
