# Generated by Django 3.2.13 on 2024-08-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_auto_20240828_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='image',
            field=models.ImageField(upload_to='pics/academics'),
        ),
    ]
