# Generated by Django 3.2.13 on 2024-09-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_websitedetail_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitedetail',
            name='my_resume',
            field=models.FileField(default='', upload_to='resume/'),
            preserve_default=False,
        ),
    ]
