# Generated by Django 3.2.13 on 2024-10-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_workexperience_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_skill', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
