# Generated by Django 3.2.13 on 2024-10-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_technicalskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalskill',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
